### ISSUE TITLE
URL redirections.

### ISSUE THREAD

**Issue by hemanth** [mozillascience/studyGroup#11]
I feel `/studyGroup` and `/studygroup` must land to the same page, as of now only the former one is active, the later on throws a 404.

According to the RFC: **Users should always consider that URLs are case-sensitive.**

So we must consider redirection.

//cc @BillMills

**Comment by sudheesh001** [comment]
I personally agree with this, The first time i tried to hit the `/studygroup` instead of the `/studyGroup`, cursed myself for the case sensitivity. :smiley:

**Comment by katieannemills** [comment]
yep, I also agree - but there's no way (that I know of) to serve something at `whoever.github.io/studygroup` to trigger a redirect to the correct url. Would love a PR showing me how it's done :)

**Comment by hemanth** [comment]
There is not `.htaccess` here but we can give [this](https://help.github.com/articles/redirects-on-github-pages/) a try...

**Comment by katieannemills** [comment]
@hemanth I played around with that at first; maybe it's just me, but I couldn't figure out how to get this to redirect to/from something that doesn't share the same base URL (`whoever.github.io/studyGroup`) - I'd be delighted to be proven wrong though!

**Comment by hemanth** [comment]
Was hoping [this](https://github.com/hemanth/studyGroup/commit/48485a219836cccfc3afca1425fbe6db80105828) would work, but no...

**Comment by katieannemills** [comment]
@hemanth cool, thanks for checking that out - I think the issue there is the [prefix](https://github.com/jekyll/jekyll-redirect-from#prefix) - what you have is redirecting from `mozillascience.github.io/studyGroup/studygroup` as far as I understand it.

**Comment by QuLogic** [comment]
Using `redirect_from` would not work as it specifies redirects on the _target_, but still has to create the _source_ URL and `/studygroup` is a _completely different repository_.

Theoretically, you could create a second repository and fill in the file that `redirect_from` would normally create. Unfortunately, while the URL is case-sensitive, GitHub does not allow creating a second repository that differs only by case.

If you really want this, I think you're going to have to open an enhancement request with GitHub itself.

**Comment by radaniba** [comment]
Try this 

https://github.com/jekyll/jekyll-redirect-from

**Comment by QuLogic** [comment]
I _just_ explained why that wouldn't work.

**Comment by radaniba** [comment]
oops my bad !

**Comment by katieannemills** [comment]
@QuLogic - thanks for digging into what's going on here! I think your assessment is correct - but, please avoid shooting down the ideas of others as above; I really appreciate you trying to help us get to a good solution, but I want everyone to feel comfortable trying things and offering suggestions - that's how the learning happens :) Trust that your mod will know what ideas will and won't work, and let the rest slide.

@hemanth, @QuLogic and others have done a great job of exploring the options here, and there doesn't seem to be a solution at this time; moving to wontfix until something happens at GitHub high command.

**Comment by hemanth** [comment]
:+1: Did any inform the high command about this? :wink:

**Comment by katieannemills** [comment]
I fired them a support request - I'll let you know if that goes anywhere, and I'll ask my GitHub people next time I see them!

**Comment by auremoser** [comment]
Thanks all for your input here, I'm going through an issue closing round, as this has been a `wont fix` for some time, I'm closing the request, if you feel strongly that this is an error, please ping me and let me know, I am happy to put some time in if anyone feels passionately about redirections.
