### ISSUE TITLE
Readme.md clarifications

### ISSUE THREAD

**Issue by ttimbers** [mozillascience/studyGroup#14]
When I followed the `Readme.md` to setup a new event I encountered a couple small issues:
1. When I tried to follow the instructions "Click on 'Issues' over on the right sidebar of your repo", I couldn't find "Issues" in the sidebar right away. I had to click "Settings" and then select "Issues" under "Features" to be able to see "Issues" in the sidebar. Only then could I click Issues to create a new event.
2. When I was creating `YYYY-MM-DD-word.markdown`, I originally put a lot of info after `location` (e.g. `location: Simon Fraser University, Burnaby Campus, SSB 6134`). When I did this no location showed up in the events on the webpage, it just looked like this: "Introduction to tidyr/reshape2 package in R by Remi Daigle,, 14 July 2015".

To solve the problem, I had removed all by SSB 6134, but I imagine just not having commas would also solve it and let me keep the other text (since "Hacky Hour Stadium" works ;p)? 

Maybe a couple notes in the `Readme.md` about how to see Issues in the sidebar and not using commas in `YYYY-MM-DD-word.markdown` could be useful?

**Comment by ttimbers** [comment]
Point #2 above could also be due to hard wrapping the text after `location:` as I normally do in an `.md` file to make it easier to read...

**Comment by katieannemills** [comment]
cool, thanks for the feedback! I've added a 'gotchas' section to the setup instructions, that point out the speedbumps people have had. Hopefully that gets people unstuck!
