### ISSUE TITLE
Types of Event

### ISSUE THREAD

**Issue by SOFTowaha** [mozillascience/studyGroup#15]
Hello people!

Can you give me some event ideas? 

Thanks
Towaha

**Comment by katieannemills** [comment]
Hi @SOFTowaha,

Sure! Check out the chapter on [event ideas](http://mozillascience.github.io/studyGroupHandbook/events.html) in the handbook; or, if you'd like something more specific, check out the events from [UBC](https://github.com/minisciencegirl/studyGroup/issues?q=label%3Aevent+is%3Aclosed), [SFU](https://github.com/ttimbers/studyGroup/issues), and [Toronto](https://github.com/UofTCoders/studyGroup/issues?q=is%3Aopen+is%3Aissue).

**Comment by SOFTowaha** [comment]
Thank you @BillMills !
