### ISSUE TITLE
Open Data at Study Groups

### ISSUE THREAD

**Issue by katieannemills** [mozillascience/studyGroup#16]
Hey everyone,

Over the next little while, I'd love to get everyone's help designing some Study Group activities on the topic of open data. How can data sharing be introduced to your Study Group in a way your colleagues will find interesting and useful? Post ideas on this thread!

It'd be awesome if each of the Study Groups tried to throw an open data session this summer. Anything you want to try out is fair game - just be sure to document it and share back here!

**Comment by tomhohenstein** [comment]
@BillMills Has anyone done sessions on [using Zenodo and GitHub together for DOIs](https://guides.github.com/activities/citable-code/)?

**Comment by aammd** [comment]
:+1:  for that; i've tried it and loved it.

**Comment by katieannemills** [comment]
Nope, not that I know of - it's a good topic for a lesson though; super useful, not particularly difficult, but weird enough the first time through that a walkthrough would be helpful. Let me know how it goes!

Another thing to possibly add on to this lesson: when to mint releases / DOI's? At every single possible change? Only on major changes? For every project, or more for projects intended as reusable components? An actual librarian knows better than me how to do this in the most useful way possible, so I'd be curious to know! I would also mention DOI history management, too - the DOI will update itself every release if the zenodo hooks are still active, so I like to keep a record in the readme of past doi's for people (invariably) using old versions, see for example [the top of this readme](https://github.com/IQuOD/wodpy).

**Comment by tomhohenstein** [comment]
great ideas! this could be a great chance to work with @stephwright : ). I'll see what I can come up with for a lesson.

**Comment by stephwright** [comment]
:+1: agree... great ideas!  We can talk about this when we chat next week, Tom!

**Comment by auremoser** [comment]
Awesome thread, and sorry for my delayed response here. These are concepts we're evolving in the [Open Data Training Series](https://github.com/mozillascience/open-data-training) that @stephwright has authored. We're building on that curriculum over the next few months to get to match our [Open Leadership Training Series](https://github.com/mozilla/open-leadership-training-series). 

Small plug for the [Moz Open Leaders Mentorship Training](https://medium.com/read-write-participate/are-you-building-in-the-open-join-forces-with-mozilla-a791dbb5c74b#.sy0hsoi40) which is taking participant applications through 1/20, ask @acabunoc for more details!
