### ISSUE TITLE
Google Calendar event management?

### ISSUE THREAD

**Issue by katieannemills** [mozillascience/studyGroup#20]
The SFU and Toronto groups have been contemplating using google calendars to help manage events. This feature could be pulled upstream, but first let's pull all the ongoing discussion threads together.
- @brunogrande patched the website to include a google calendar [here](https://github.com/ttimbers/studyGroup/commit/132ab333fd9e670178767eb8f9fa9c613bbb69a3) - we'll pull this upstream as part of this feature.
- @theavanrossum is working on a script to automatically manage the calendar from the yml in the `_posts` directory.
  - but, how does this handle times? time of day isn't in the yml (which is kind of weird, now that you mention it); will probably add a time field to these stubs to solve this.

Any other ideas or concerns? cc @lannajin @mbonsma @ttimbers, [this issue](https://github.com/UofTCoders/studyGroup/issues/25)

**Comment by katieannemills** [comment]
If there are no comments or problems, I'm going to go ahead and promote this feature to the main template this week(ish). @theavanrossum, is that script for managing calendars available for sharing? Would love a pull request against the [upstream repo](https://github.com/mozillascience/studyGroup) to include that script & show who wrote it in the commit history. Thanks, all!

**Comment by theavanrossum** [comment]
Just finishing up the script improvements now. 
Available here:
https://github.com/ttimbers/studyGroup/blob/gh-pages/createEventsFromPosts_clearCalendarFirst.py

A few fixes:
- I have default start and end times hard coded in the script, but these are overridden if "startTime" or "endTime" are in the _post file
- the script now deletes all calendar posts before creating new ones

Still to do:
- Should be able to use git hooks to trigger running this script automagically

**Comment by katieannemills** [comment]
works great for me, thanks for this! I'm going to merge this in as is, and add the start and end time metadata you recommend. Thanks!

**Comment by katieannemills** [comment]
Alright - this feature merged to gh-pages. Great work everyone, and open an issue if you'd like me to PR you the commits necessary to add this feature to your Study Group. Thanks all!
