### ISSUE TITLE
License for code of conduct?

### ISSUE THREAD

**Issue by blahah** [mozillascience/studyGroup#32]
I see that the repo in general is Apache2 licensed. I'm wondering whether this applies to text-only parts of the repo, like the code of conduct? I ask because it's unusual to apply a code-specific license like Apache to text, when more specific licenses (i.e. Creative Commons ones) exist.

**Comment by katieannemills** [comment]
Hm - that got inherited from the jekyll template, not intended to apply to the rest of the content. The MSL code of conduct is cc-by (or 0, I forget) in its original incarnation on their website.
