### ISSUE TITLE
Anyone using Gitter Sidecar?

### ISSUE THREAD

**Issue by tomhohenstein** [mozillascience/studyGroup#39]
Hello! 

I'm looking into adding [Gitter's Sidecar](https://sidecar.gitter.im/) to our Study Group website and I'm curious if anyone has already done this. It seems to work "out of the box" but I'm having on3 issue with the scrolling - only the page scrolls not the chat room. 

Any thoughts? 

Tom

**Comment by katieannemills** [comment]
Hey Tom,

We're using sidecar over at ResBaz: https://2016-02-01.resbaz.com/
(which, btw, is an awesome event everyone should check out :)

Does the resbaz site behave the same as yours? The 'open chat' tab has a
fixed position out of the box; is this not what you want?

On Mon, Nov 16, 2015 at 1:06 PM, Tom Hohenstein notifications@github.com
wrote:

> Hello!
> 
> I'm looking into adding Gitter's Sidecar https://sidecar.gitter.im/ to
> our Study Group website and I'm curious if anyone has already done this. It
> seems to work "out of the box" but I'm having on3 issue with the scrolling
> - only the page scrolls not the chat room.
> 
> Any thoughts?
> 
> Tom
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozillascience/studyGroup/issues/39.

## 

Best Regards,
Dr. Bill Mills
TRIUMF

**Comment by tomhohenstein** [comment]
Hi Bill, 

re: resbaz -> very cool - thanks for sharing. 

It does have the same functionality - I'm assuming scrolling up to view past conversations in sidecar is not a top priority. Curious that the demo - https://sidecar.gitter.im/ - allows scrolling within the sidecar.

**Comment by katieannemills** [comment]
Sidecar conversations scroll up for me, in FF 41.0.2 - what browser are you using? Might be worth opening a ticket with them if the behavior isn't consistent across browsers.

**Comment by tomhohenstein** [comment]
Got it to work! I added a few more lines of chat and that seemed to make it long enough for it to engage the scrolling. 

thanks!

**Comment by RaoOfPhysics** [comment]
Is this something that can be added as default functionality for Study Group websites (toggled by the `yml` config file, perhaps)? Are there any disadvantages to doing so?

See https://github.com/CERNStudyGroup/cernstudygroup.github.io/issues/13

**Comment by auremoser** [comment]
Whoa, throwback Tuesday with the issue comments (sorry @RaoOfPhysics ) ...I'm not sure it's valuable as a debug in the main repo, since a separate gitter window would be feasible enough to keep open during meetups with remote participants. 

I think the chat window in whatever program you use to record or video chat your sessions might be more valuable, like hangouts or vidyo. Closing this for now since sidecar doesn't seem to be an easy integration on cursory gander.
