### ISSUE TITLE
Mozilla Study Groups December Update

### ISSUE THREAD

**Issue by katieannemills** [mozillascience/studyGroup#43]
# Welcome New Study Groups

Welcome to our newest Study Group at [Rhode Island](http://rhodyrstats.org/)! More Study Groups are spooling up around the world; we'll note them here and add them to the [Study Group Map](https://github.com/mozillascience/studyGroupLessons/blob/master/whereWeAre.geojson) as their first events come on line. Have you started a new group recently? Make sure to let us know so we can get you on the map!
# Mozilla Study Groups Year One

With the New Year almost here, I took a minute to look back on what we've done together in our first year: you have delivered **over 140 events and 46 open lesson plans at over 20 sites in less than a year.** Each and every one of you has done tremendous work, and should be really proud of the communities you have helped create in your home towns and around the world. This was your energy, your skill, and your enthusiasm that built this; well done all!

To celebrate, I hope everyone has a party planned! I know [Vancouver](https://github.com/minisciencegirl/studyGroup/issues/73) and [Toronto](https://github.com/UofTCoders/Events/issues/25) do - this time of year is a great chance to invite your community to get together for a [Hacky Hour](http://mozillascience.github.io/studyGroupHandbook/event-types.html#hackyhour) or other get-together to look back on what you accomplished this year, thank them for participating, and reflect on how we can do even better next year.
# Planning for 2016

Speaking of going even further next year, with a new semester already coming up in just a few weeks, now is a great time to figure out how we can do better than ever before; a couple of to-do's for everyone:
- **Participants:** We want to make contributing to Study Group as fun and rewarding as possible for you, so we're working on [a draft of some Contributor Guidelines](https://public.etherpad-mozilla.org/p/SGContributorGuidelines) - help us out by **adding any questions or challenges you've had** trying to contribute or participate at the bottom of the draft, so we can try and weave in as many solutions as possible.
- **Organizers:** The [Study Group Handbook](http://mozillascience.github.io/studyGroupHandbook/index.html) is where we collect everyone's experience running a Study Group; it needs your input to get better! If you've helped organize a Study Group (and especially if you're just starting out!), **open an issue [here](https://github.com/mozillascience/studyGroupHandbook/issues) describing one thing you wish you'd known** when you first started. By updating the Handbook to address all these, we can make starting a Mozilla Study Group even easier for all our new colleagues we'll be meeting in 2016.

Once more - a huge THANK YOU to everyone who has jumped on board with Mozilla Study Groups in its first year; this program was founded to bring people together to share their skills and experiences, and you have all helped make that a reality and a huge success - and I am confident that these past successes are only to be outdone by our future ones.

**Comment by tomhohenstein** [comment]
I think we can close this one : )
