### ISSUE TITLE
Showing previous events

### ISSUE THREAD

**Issue by anelda** [mozillascience/studyGroup#44]
Hi everyone, we're at the Mozilla Science WOW workshop in  Berlin and a few of us were discussing the idea that we'd like to also display previous events on the website.

Are there any plans to do that in the template or does anyone have a suggestion to go about this?

**Comment by ttimbers** [comment]
We have a button ("See all events") under the events header that shows past
events for the SFU study group: http://sciprog.ca/

On Fri, Feb 5, 2016 at 8:24 AM, Anelda van der Walt <
notifications@github.com> wrote:

> Hi everyone, we're at the Mozilla Science WOW workshop in Berlin and a few
> of us were discussing the idea that we'd like to also display previous
> events on the website.
> 
> Are there any plans to do that in the template or does anyone have a
> suggestion to go about this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozillascience/studyGroup/issues/44.

## 

Tiffany A. Timbers, PhD
Banting Postdoctoral fellow, Leroux Lab
Department of Molecular Biology and Biochemistry
Simon Fraser University
8888 University Drive
Burnaby, BC, V5A 1S6

604-803-4962

tiffany.timbers@gmail.com
tiffanytimbers.com
@TiffanyTimbers

**Comment by ttimbers** [comment]
Note - it only does this for the current year...

On Fri, Feb 5, 2016 at 8:26 AM, Tiffany Timbers tiffany.timbers@gmail.com
wrote:

> We have a button ("See all events") under the events header that shows
> past events for the SFU study group: http://sciprog.ca/
> 
> On Fri, Feb 5, 2016 at 8:24 AM, Anelda van der Walt <
> notifications@github.com> wrote:
> 
> > Hi everyone, we're at the Mozilla Science WOW workshop in Berlin and a
> > few of us were discussing the idea that we'd like to also display previous
> > events on the website.
> > 
> > Are there any plans to do that in the template or does anyone have a
> > suggestion to go about this?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mozillascience/studyGroup/issues/44.
> 
> ## 
> 
> Tiffany A. Timbers, PhD
> Banting Postdoctoral fellow, Leroux Lab
> Department of Molecular Biology and Biochemistry
> Simon Fraser University
> 8888 University Drive
> Burnaby, BC, V5A 1S6
> 
> 604-803-4962
> 
> tiffany.timbers@gmail.com
> tiffanytimbers.com
> @TiffanyTimbers

## 

Tiffany A. Timbers, PhD
Banting Postdoctoral fellow, Leroux Lab
Department of Molecular Biology and Biochemistry
Simon Fraser University
8888 University Drive
Burnaby, BC, V5A 1S6

604-803-4962

tiffany.timbers@gmail.com
tiffanytimbers.com
@TiffanyTimbers

**Comment by katieannemills** [comment]
Can you sketch out what you'd like this to look like (like on paper)? It's
certainly possible!

On Friday, 5 February 2016, Anelda van der Walt notifications@github.com
wrote:

> Hi everyone, we're at the Mozilla Science WOW workshop in Berlin and a few
> of us were discussing the idea that we'd like to also display previous
> events on the website.
> 
> Are there any plans to do that in the template or does anyone have a
> suggestion to go about this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozillascience/studyGroup/issues/44.

## 

Best Regards,
Dr. Bill Mills
TRIUMF

**Comment by anelda** [comment]
Thanks Tiffany, I like what you have.  Bill, something like that will be good - but even something similar to the Software Carpentry website will work - they show upcoming workshops and previous workshops. Currently if you have no upcoming events on your website it looks like you've never had anything (you'd have to go to the repo to see that there is actually some activity)

**Comment by katieannemills** [comment]
Cool - @ttimbers, are the commits with that feature well-factored enough to cherry pick them onto a branch, PR them upstream and distribute from there? If they're tied up with other stuff, I can implement something like that feature upstream perhaps this weekend.

**Comment by ttimbers** [comment]
I am not sure, either @brunogrande or @theavanrossum implemented this
feature (I think).

On Fri, Feb 5, 2016 at 9:09 AM, Bill Mills notifications@github.com wrote:

> Cool - @ttimbers https://github.com/ttimbers, are the commits with that
> feature well-factored enough to cherry pick them onto a branch, PR them
> upstream and distribute from there? If they're tied up with other stuff, I
> can implement something like that feature upstream perhaps this weekend.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozillascience/studyGroup/issues/44#issuecomment-180444908
> .

## 

Tiffany A. Timbers, PhD
Banting Postdoctoral fellow, Leroux Lab
Department of Molecular Biology and Biochemistry
Simon Fraser University
8888 University Drive
Burnaby, BC, V5A 1S6

604-803-4962

tiffany.timbers@gmail.com
tiffanytimbers.com
@TiffanyTimbers

**Comment by katieannemills** [comment]
ok! I can implement a simple hide / show toggle for past posts in approximately the same amount of time as doing any complicated git surgery, so if the feature branch isn't obvious that might be the way to go.

**Comment by BrunoGrandePhD** [comment]
I implemented the "See All Events" page. Unfortunately, that feature was implemented alongside various other visual improvements. You'll have to cherry-pick, but revert some of the updated files. See the following pull request. 

https://github.com/ttimbers/studyGroup/pull/42

Also, I meant the "Past Events" section to include all past events. I tried my best, but I dislike the way Liquid handles dates. @BillMills, maybe you can tweak `_includes/events.html` to work as expected.

**Comment by katieannemills** [comment]
Sure, I'll try and cook something up soon. Thanks!

**Comment by anelda** [comment]
Thanks everyone for your speedy responses! Thanks Bill :smiley:

**Comment by katieannemills** [comment]
Alright - a demo of this new feature is live at http://mozillascience.github.io/studyGroup/, in the Events section.

If you like the look of this, the feature branch is `past-events` in this repo - let me know if you'd like me to help set up a pull request. Thanks everyone for your feedback and ideas!
