### ISSUE TITLE
RFC: Issue templates for event info / lesson suggestions

### ISSUE THREAD

**Issue by RaoOfPhysics** [mozillascience/studyGroup#52]
It would be nice if issues created for upcoming Study Group events or for lesson suggestions followed a standard format, something along the lines of:

> Date: ___
> Location: ___
> Session format: Hacky Hour / Code-Along / Etc.
> Lesson guide (if applicable): ___
> Lesson materials (if applicable): ___
> ---
> 
> [BODY]

This can be implemented using GitHub's [Issue templates](https://github.com/blog/2111-issue-and-pull-request-templates).

See, for example, https://github.com/CERNStudyGroup/cernstudygroup.github.io/issues/20 (more: https://github.com/CERNStudyGroup/cernstudygroup.github.io/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3ALesson).

Happy to create the template for approval if you think this is worth doing. :)

**Comment by abbycabs** [comment]
Are all issues going to be events or lessons? I think some groups use this for discussion, too, so I'm not sure how applicable a template like this would be for each group.

Some study group leads may have more insight here! @mbonsma, @auremoser?

**Comment by RaoOfPhysics** [comment]
@acabunoc: As I understand it, users are free to ignore the [templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/), so it shouldn't be a problem. But for those who want to propose an event, it would be good to stick to a format so that the org members don't have to go in and clean up all the time. :)

**Comment by mbonsma** [comment]
We use separate repos for [events](https://github.com/UofTCoders/Events/issues) and [general discussion](https://github.com/UofTCoders/studyGroup/issues), so a template would be very appropriate in the Events repo in our case. 

It might be nice to have a template in the handbook or something, but leave it up to individual groups to implement because needs might be different depending on the group.

**Comment by auremoser** [comment]
We discussed this, sort of. I think implementing upstream would be worth investigating. i don't want top pressure people into adopting templates, but I would be cool to have a standard for a collaborative global Study Group calendar. 

How do the current events work for most folks? Does everyone have a separate repo? It might make sends to give issue labels according to the type of event Hacky Hour, Code-along etcet. I could put one in the hidden .github directory and add a note in the handbook for post-facto forks, plus email the list about doing a pull if they are interested in integrating.

Might be a nice topic for the next Study Group call too.

**Comment by auremoser** [comment]
Way belated followup here, but we've added a [lessons template](https://github.com/mozillascience/studyGroup/blob/gh-pages/lesson-template.md), thanks @zee-moz . And it also exists as an issue template in the [Lessons Repo](https://github.com/mozillascience/studyGroupLessons) for study groups, [template here](https://github.com/mozillascience/studyGroupLessons/blob/master/ISSUE_TEMPLATE.md), which auto-populates when you create a new issue or lesson submission. 

Closing this issue for the time being, to keep things tidy!
