### ISSUE TITLE
Potential Pan-African study group

### ISSUE THREAD

**Issue by blahah** [mozillascience/studyGroup#56]
There are already (at least) three study groups in Africa:
- [Tunis, Tunisia](http://amelgh.github.io/IPT_Tunisia/) run by @amelgh
- [Khartoum, Sudan](http://zo0z.github.io/studyGroup/) run by @zo0z
- [North-West University, South Africa](http://anelda.github.io/GenomicsHackyHour/) run by @anelda

Several organisations around Africa and that operate all over Africa (including H3ABionet and TrendInAfrica) have been discussing creating an umbrella study group.

The idea would be to have some of the resources of the local groups but at a continental level. For example, there could be a slack or gitter channel for the Pan-African group, and there could be hangouts or other video meetings, or local meetups could be broadcast to the whole continent. 

I'm just creating this issue as a visible space to talk about setting this up, and loop in Mozilla folks.

**Comment by auremoser** [comment]
Thanks @blahah , super-belated but we have semi-regular checkins with @amelgh + @anelda. @zo0z would you like to be involved as well?

**Comment by azzaea** [comment]
Absolutely! Thank you for this!

**Comment by auremoser** [comment]
Great, you've been added, I'm closing this issue for the time being! :)
