### ISSUE TITLE
Update Portuguese README to match English

### ISSUE THREAD

**Issue by auremoser** [mozillascience/studyGroup#76]
## Context
We're trying to better localize our Study Groups introduction README for different languages.

## Description
We recently updated our [README](https://github.com/mozillascience/studyGroup/blob/gh-pages/README.md) in english, and changed much of the language associated with how to get started with Study Groups. We previously had a lovely translation in [Portuguese for the README]() but have not yet updated it to match the changes in English. Please help if you can!

## Steps
* Look at the english [README](https://github.com/mozillascience/studyGroup/blob/gh-pages/README.md)
* Fork this Study Groups [Repo](https://github.com/mozillascience/studyGroup)
* In Terminal:
 * `clone [ssh key for Study Groups fork]`
 *  `cd [path to studyGroup repo on your local computer]`
* Open the [README](https://github.com/mozillascience/studyGroup/blob/gh-pages/README.md) and the [README-pt.md](https://github.com/mozillascience/studyGroup/blob/gh-pages/README-pt.md) in a text editor
* Translate the README-pt to match the english as close as possible, save changes
* Commit changes and submit a pull request to update the Portuguese translation
  * `git status`
  * `git commit -m "SOME COMMENT ABOUT YOUR CHANGES"`
  * `git push origin master`

:tada:

## References
* [README in English](https://github.com/mozillascience/studyGroup/blob/gh-pages/README.md) - the main and up-to-date source of content
* [README in Portuguese](https://github.com/mozillascience/studyGroup/blob/gh-pages/README-pt.md) - the translation of the main Readme
* [README in Hindi](https://github.com/mozillascience/studyGroup/blob/gh-pages/README-hi.md) - a translation example that has been updated to match the english

**Comment by elionaimc** [comment]
Translation done.
Waiting someone do accept my pull request.

**Comment by elionaimc** [comment]
Added portuguese translation file to lesson template.

**Comment by auremoser** [comment]
Hurray! Thank you so much @elionaimc !!!!
