### ISSUE TITLE
img/portfolio/{{post.img}} throws 404 error

### ISSUE THREAD

**Issue by sudheesh001** [mozillascience/studyGroup#9]
On the home page, there's no content present in the `{{post.img}}`

``` html
<div class="modal-body">
       <h2>Make Your First Event</h2>
                 <hr class="star-primary">
                 <img src="img/portfolio/" class="img-responsive img-centered" alt="">
                 <p></p>
       <ul class="list-inline item-details">
                 <li>Client:
                       <strong><a href="http://startbootstrap.com"></a></strong>
                 </li>
                 <li>Date:
                      <strong><a href="http://startbootstrap.com"></a></strong>
                 </li>
                 <li>Service:
                      <strong><a href="http://startbootstrap.com"></a></strong>
                 </li>
        </ul>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
</div>
```

The `<img src="img/portfolio/" class="img-responsive img-centered" alt="">`

Error thrown:
`GET http://mozillascience.github.io/studyGroup/img/portfolio/ 404 (Not Found)                mozillascience.github.io/:212`

Link to reproduce error: `http://mozillascience.github.io/studyGroup/`
Best way to avoid this is to make sure that the `<img>` is only rendered if the `{{post.img}}` has a value other than `Null`

**Comment by katieannemills** [comment]
Great catch @hemanth & @sudheesh001 - now that you point it out, the whole `modals` bit is actually a leftover from the original template, we can pull it out altogether; but this patch makes things tighter if we ever decide to use it again, thanks!

**Comment by hemanth** [comment]
:+1:
